//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, vhudson-jaxb-ri-2.1-520
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2008.03.03 at 11:23:03 上午 CST
//

package com.common.config;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
 *       &lt;sequence&gt;
 *         &lt;element name=&quot;prop&quot; type=&quot;{}Prop&quot; maxOccurs=&quot;unbounded&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element name=&quot;dictionary&quot; type=&quot;{}Dictionary&quot;/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "prop", "dictionary" })
@XmlRootElement(name = "configuration")
public class Configuration
{

	protected List<Prop> prop;
	@XmlElement(required = true)
	protected Dictionary dictionary;

	/**
	 * Gets the value of the prop property.
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the prop property.
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getProp().add(newItem);
	 * </pre>
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link Prop }
	 */
	public List<Prop> getProp()
	{
		if (prop == null)
		{
			prop = new ArrayList<Prop>();
		}
		return this.prop;
	}

	/**
	 * Gets the value of the dictionary property.
	 * 
	 * @return possible object is {@link Dictionary }
	 */
	public Dictionary getDictionary()
	{
		return dictionary;
	}

	/**
	 * Sets the value of the dictionary property.
	 * 
	 * @param value allowed object is {@link Dictionary }
	 */
	public void setDictionary(Dictionary value)
	{
		this.dictionary = value;
	}

	public void setPropListener(final Listener l)
	{
		prop = (l == null) ? null : new ArrayList<Prop>()
		{
			private static final long serialVersionUID = 4115731994945990351L;

			public boolean add(Prop o)
			{
				l.handleProp(Configuration.this, o);
				return super.add(o);
			}
		};
	}

	/**
	 * This listener is invoked every time a new prop is unmarshalled.
	 */
	public static interface Listener
	{
		void handleProp(Configuration conf, Prop o);
	}
}
