//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, vhudson-jaxb-ri-2.1-520
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2008.03.03 at 11:23:03 上午 CST
//

package com.common.config;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for Dictionary complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name=&quot;Dictionary&quot;&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
 *       &lt;sequence&gt;
 *         &lt;element name=&quot;category&quot; maxOccurs=&quot;unbounded&quot; minOccurs=&quot;0&quot;&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name=&quot;entry&quot; type=&quot;{}Entry&quot; maxOccurs=&quot;unbounded&quot; minOccurs=&quot;0&quot;/&gt;
 *                 &lt;/sequence&gt;
 *                 &lt;attribute name=&quot;enName&quot; use=&quot;required&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot; /&gt;
 *                 &lt;attribute name=&quot;chName&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot; /&gt;
 *                 &lt;attribute name=&quot;def&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot; /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Dictionary", propOrder = { "category" })
public class Dictionary
{

	protected List<Dictionary.Category> category;

	/**
	 * Gets the value of the category property.
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the category property.
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getCategory().add(newItem);
	 * </pre>
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link Dictionary.Category }
	 */
	public List<Dictionary.Category> getCategory()
	{
		if (category == null)
		{
			category = new ArrayList<Dictionary.Category>();
		}
		return this.category;
	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType&gt;
	 *   &lt;complexContent&gt;
	 *     &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
	 *       &lt;sequence&gt;
	 *         &lt;element name=&quot;entry&quot; type=&quot;{}Entry&quot; maxOccurs=&quot;unbounded&quot; minOccurs=&quot;0&quot;/&gt;
	 *       &lt;/sequence&gt;
	 *       &lt;attribute name=&quot;enName&quot; use=&quot;required&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot; /&gt;
	 *       &lt;attribute name=&quot;chName&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot; /&gt;
	 *       &lt;attribute name=&quot;def&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot; /&gt;
	 *     &lt;/restriction&gt;
	 *   &lt;/complexContent&gt;
	 * &lt;/complexType&gt;
	 * </pre>
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "entry" })
	public static class Category
	{
		protected List<Entry> entry;
		@XmlAttribute(required = true)
		protected String enName;
		@XmlAttribute
		protected String chName;
		@XmlAttribute
		protected String def;

		/**
		 * Gets the value of the entry property.
		 * <p>
		 * This accessor method returns a reference to the live list, not a
		 * snapshot. Therefore any modification you make to the returned list
		 * will be present inside the JAXB object. This is why there is not a
		 * <CODE>set</CODE> method for the entry property.
		 * <p>
		 * For example, to add a new item, do as follows:
		 * 
		 * <pre>
		 * getEntry().add(newItem);
		 * </pre>
		 * 
		 * <p>
		 * Objects of the following type(s) are allowed in the list
		 * {@link Entry }
		 */
		public List<Entry> getEntry()
		{
			if (entry == null)
			{
				entry = new ArrayList<Entry>();
			}
			return this.entry;
		}

		/**
		 * Gets the value of the enName property.
		 * 
		 * @return possible object is {@link String }
		 */
		public String getEnName()
		{
			return enName;
		}

		/**
		 * Sets the value of the enName property.
		 * 
		 * @param value allowed object is {@link String }
		 */
		public void setEnName(String value)
		{
			this.enName = value;
		}

		/**
		 * Gets the value of the chName property.
		 * 
		 * @return possible object is {@link String }
		 */
		public String getChName()
		{
			return chName;
		}

		/**
		 * Sets the value of the chName property.
		 * 
		 * @param value allowed object is {@link String }
		 */
		public void setChName(String value)
		{
			this.chName = value;
		}

		/**
		 * Gets the value of the def property.
		 * 
		 * @return possible object is {@link String }
		 */
		public String getDef()
		{
			return def;
		}

		/**
		 * Sets the value of the def property.
		 * 
		 * @param value allowed object is {@link String }
		 */
		public void setDef(String value)
		{
			this.def = value;
		}

		public void setEntryListener(final Listener l)
		{
			entry = (l == null) ? null : new ArrayList<Entry>()
			{
				private static final long serialVersionUID = 1311061791240170371L;

				public boolean add(Entry o)
				{
					l.handleEntry(Category.this, o);
					return super.add(o);
				}
			};
		}

		/**
		 * This listener is invoked every time a new entry is unmarshalled.
		 */
		public static interface Listener
		{
			void handleEntry(Category cate, Entry o);
		}

	}

	public void setCategoryListener(final Listener l)
	{
		category = (l == null) ? null : new ArrayList<Category>()
		{
			private static final long serialVersionUID = 4115731994945990351L;

			public boolean add(Category o)
			{
				l.handleCategory(Dictionary.this, o);
				return super.add(o);
			}
		};
	}

	public static interface Listener
	{
		void handleCategory(Dictionary dict, Category o);
	}
}
